
import { Inter, Open_Sans } from "next/font/google";

const OpenSans = Open_Sans({
    subsets: ["latin"],
    display: "swap"
});

export const metadata = {
    title: "dots",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div
            // className={OpenSans.className}
        >
            {children}
        </div>
    );
}
