import Link from "next/link";
import { Suspense } from "react";
import LoadingFullPage from "./loading";
import "./globals.css";
import Provider from "@/components/Provider";
import { PageWrapper } from "@/components/config/pageWrapper";
import { Inter } from "next/font/google";

import { useState } from "react";

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
});
import localFont from "next/font/local";
import { Navbar, AsideNavbar } from "@/components/Navbar";
import BasicBody from "@/components/Provider copy";

const HelveticaNowText = localFont({
    src: [
        {
            path: "../fonts/HelveticaNowText/HelveticaNowText-Thin.woff2",
            weight: "100",
            style: "normal",
        },
        {
            path: "../fonts/HelveticaNowText/HelveticaNowText-ThinItalic.woff2",
            weight: "100",
            style: "italic",
        },
        {
            path: "../fonts/HelveticaNowText/HelveticaNowText-ExtraLight.woff2",
            weight: "200",
            style: "normal",
        },
        {
            path: "../fonts/HelveticaNowText/HelveticaNowText-ExtLtIta.woff2",
            weight: "200",
            style: "italic",
        },
        {
            path: "../fonts/HelveticaNowText/HelveticaNowText-Light.woff2",
            weight: "300",
            style: "normal",
        },
        {
            path: "../fonts/HelveticaNowText/HelveticaNowText-LightItalic.woff2",
            weight: "300",
            style: "italic",
        },
        {
            path: "../fonts/HelveticaNowText/HelveticaNowText-Regular.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "../fonts/HelveticaNowText/HelveticaNowText-RegIta.woff2",
            weight: "400",
            style: "italic",
        },
        {
            path: "../fonts/HelveticaNowText/HelveticaNowText-Medium.woff2",
            weight: "500",
            style: "normal",
        },
        {
            path: "../fonts/HelveticaNowText/HelveticaNowText-MediumItalic.woff2",
            weight: "500",
            style: "italic",
        },
        {
            path: "../fonts/HelveticaNowText/HelveticaNowText-Bold.woff2",
            weight: "700",
            style: "normal",
        },
        {
            path: "../fonts/HelveticaNowText/HelveticaNowText-BoldItalic.woff2",
            weight: "700",
            style: "italic",
        },
        {
            path: "../fonts/HelveticaNowText/HelveticaNowText-ExtraBold.woff2",
            weight: "800",
            style: "normal",
        },
        {
            path: "../fonts/HelveticaNowText/HelveticaNowText-ExtBdIta.woff2",
            weight: "800",
            style: "italic",
        },
        {
            path: "../fonts/HelveticaNowText/HelveticaNowText-Black.woff2",
            weight: "900",
            style: "normal",
        },
        {
            path: "../fonts/HelveticaNowText/HelveticaNowText-BlackItalic.woff2",
            weight: "900",
            style: "italic",
        },
    ],
});

export const metadata = {
    title: "dots",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    // primary: emerald-300
    // secondary: emerald-200
    // background: bg-neutral-900
    // main test: neutral-300

    return (
        <html lang="pt-br">
            <body
                className={
                    HelveticaNowText.className +
                    ` 
                        bg-gray-200 h-screen text-neutral-800
                        relative
                        flex flex-col 
                    `
                }
            >
                <Provider>
                    <main className="px-4 py-8 w-auto min-h-screen z-10">
                        <AsideNavbar>
                            <Suspense fallback={<LoadingFullPage />}>{children}</Suspense>
                        </AsideNavbar>
                    </main>
                </Provider>
            </body>
        </html>
    );
}
