import Link from "next/link";
import "./globals.css";
import Provider from "@/components/Provider";
import { Inter } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
    subsets: ["latin"],
    display: "swap",
});
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";

// Font files can be colocated inside of `app`
const pretendard = localFont({
    src: "../fonts/PretendardVariable.woff2",
    display: "auto",
});

export const metadata = {
    title: "dots",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    // primary: emerald-300
    // secondary: emerald-200
    // background: bg-neutral-900
    // main test: neutral-300
    return (
        <html lang="pt-br">
            <body
                className={
                    pretendard.className +
                    ` 
                        bg-gray-200 h-screen text-neutral-800
                        mt-16
                    `
                }
            >
                <Provider>
                    <header className="relative">
                        <Navbar />
                    </header>
                    <main>{children}</main>
                </Provider>
            </body>
        </html>
    );
}
