import Link from "next/link";

import { Inter, Open_Sans } from "next/font/google";

const OpenSans = Open_Sans({
    subsets: ["latin"],
    display: "swap",
});

import { Navbar, MobileMenu } from "@/components/navbar/Nav";
import BasicBody from "@/components/Provider copy";

import CreatePostBtn from "@/components/navbar/CreatePostBtn";

export const metadata = {
    title: "dots",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div
            className={`
                p-4 max-md:p-0
                max-w-screen-lg lg:w-[1024px] lg:m-auto
                
            `}
        >
            {children}
            <MobileMenu />
            <CreatePostBtn />
        </div>
    );
}
